services:
  db:
    image: postgres:17-alpine
    container_name: orientta_db
    environment:
      POSTGRES_USER: orientta_admin
      POSTGRES_PASSWORD: orientta_pass
      POSTGRES_DB: orientta_hunter
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: orientta_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: orientta_frontend
    ports:
      - "3000:3000"
